version: "3.1"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 7654:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - $(which docker):/usr/bin/docker jenkins/jenkins:lts
volumes:
  jenkins_home:
