version: "3"
services:
  mongo:
    image: "mongo:4.4-bionic"
    container_name: "mongo-db"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    # restart: unless-stopped
    command: mongod
    # networks:
    #   - node_network

volumes:
  mongodata: null
