version: "3.1"
services:
  db:
    image: mysql:latest
    container_name: mysql-database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=duracell
      - MYSQL_DATABASE=database
      # - MYSQL_USER=mysql_user
      # - MYSQL_PASSWORD=duracell
      # - PMA_ARBITRARY=1
    ports:
      - 3306:3306
    volumes:
      - mydb:/var/lib/mysql
    networks:
      - node_network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    container_name: phpmyadmin
    networks:
      - node_network

volumes:
  mydb: null

networks:
  node_network:
    driver: bridge
